[project]
name = "apuestas-deportivas"
version = "0.1.0"
description = "LibrerÃ­a para simular apestas deportivas reales, con ganador y premio."
authors = [{name="Marcos Almorox"}]
readme = "README.md"
requires-python = ">=3.8"